name: gila-integrator
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - matplotlib=3.10
  - scipy=1.15
  - numpy=2.2
  - fpm=0.11
  - ford=7.0.10
prefix: /home/nch/miniforge3/envs/gila-integrator
